server:
  port: 8080

spring:
  application:
    name: recommendation
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 406020484448-uidiges80gsvmu4dsdrlpgcl5j506rmv.apps.googleusercontent.com
            client-secret: I1Ln6Sryc5AjkbF2b5_D5Nbm

#logging:
#  level:
#    org.springframework.security: DEBUG
