server:
  port: 8080

spring:
  application:
    name: recommendation
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: <<clientId>>
            client-secret: <<client-secret>>

#logging:
#  level:
#    org.springframework.security: DEBUG
